name: web_laba_2
description: "Client for web laba 2"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  extra_pedantic: ^4.0.0
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0
  get_it: ^7.7.0
  injectable: ^2.4.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  topg:
    path: ../../features/topg
  i18n:
    path: ../../features/i18n

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
