name: web_laba_2
description: "Client for web laba 2"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  extra_pedantic: ^4.0.0
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0
  topg:
    path: ../../features/topg
  i18n:
    path: ../../features/i18n

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
