name: topg
description: "TopG components library."

publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  freezed: ^2.5.0
  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.6
  extra_pedantic: ^4.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.9


flutter:
  generate: true
  uses-material-design: true
