name: digital_sobol_group_testing
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.5.1
  get_it: ^7.6.7
  injectable: ^2.3.5
  cupertino_icons: ^1.0.6
  riverpod: ^2.5.1
  provider: ^6.1.2
  auto_route: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  auto_route_generator: ^8.0.0
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
